export const CRON_META = {
  NAME: 'NAME',
  PATTERN: 'PATTERN',
  ACTIVE: 'ACTIVE',
  OVERLAP: 'OVERLAP',
  RUN_ON_INIT: 'RUN_ON_INIT',
  PULL_OUT: 'PULL_OUT',
  DESCRIPTION: 'DESCRIPTION',
  METHOD: 'METHOD'
}

export const CRON_DEBUG = 'CRON_DEBUG'